package com.evan.lejo.configuration.response;

public interface Error {

    String ORDER_STATUS_REQUIRED                 = "ORDER_STATUS_REQUIRED";
    String ORDER_STATUS_INVALID                  = "ORDER_STATUS_INVALID";
    String ACCOUNT_USERNAME_REQUIRED             = "ACCOUNT_USERNAME_REQUIRED";
    String ACCOUNT_PASSWORD_REQUIRED             = "ACCOUNT_PASSWORD_REQUIRED";
    String ACCOUNT_INFORMATION_MOBILE_REQUIRED   = "ACCOUNT_INFORMATION_MOBILE_REQUIRED";
    String ACCOUNT_INFORMATION_MOBILE_INVALID    = "ACCOUNT_INFORMATION_MOBILE_INVALID";
    String ACCOUNT_INFORMATION_ADDRESS_REQUIRED  = "ACCOUNT_INFORMATION_ADDRESS_REQUIRED";
    String ACCOUNT_INFORMATION_CITY_REQUIRED     = "ACCOUNT_INFORMATION_CITY_REQUIRED";
    String ACCOUNT_INFORMATION_POSTCODE_REQUIRED = "ACCOUNT_INFORMATION_POSTCODE_REQUIRED";
    String DISH_PRICE_NOT_ALLOWED                = "DISH_PRICE_NOT_ALLOWED";
}
